/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ModernOffice = (props) => {
  const { nodes, materials } = useGLTF('/models/a_modern_it_office_wo_0116122530_texture.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  )
}

useGLTF.preload('/models/a_modern_it_office_wo_0116122530_texture.glb')
export default ModernOffice