/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const Profile3D = (props) => {
  const { nodes, materials } = useGLTF('/models/profile3d.glb')

    const profileRef = useRef();
      useGSAP(() => {
          gsap.to(profileRef.current.rotation, {
            y:0.3,
            duration: 5,  
            repeat: -1,     
            yoyo: true,    
            ease: "linear", 
          });
        }, []);
  return (
    <group {...props} scale={2.5} ref={profileRef} rotation={[0,-0.3,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  )
}

useGLTF.preload('/models/profile3d.glb')

export default Profile3D;