/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Suyog modak (https://sketchfab.com/Suyogmdk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-flying-robot-5fe620336cbd497ab68c80b2a2a7b261
Title: SCI - FI Flying Robot.
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const RoboBot = (props) => {
  const { nodes, materials } = useGLTF('/models/sci_-_fi_flying_robot..glb')
    const target = useRef();

    useGSAP(()=> {
        // gsap.to(target.current.position, {
        //     y:target.current.position.y + 3,
        //     duration: 1.2,
        //     yoyo: true,
        //     repeat:-1
        // })
        gsap.to(target.current.rotation, {
            z:target.current.rotation.z + 3,
            duration:5,
            repeat:-1,
            yoyo:true
        })
    })

  return (
    <Float floatIntensity={2}>
      <group {...props} scale={0.22} rotation={[-Math.PI / 1.8, 0, 0]} ref={target}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.aiStandardSurface2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.blinn2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.aiStandardSurface5SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.aiStandardSurface4SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.aiStandardSurface6SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.aiStandardSurface6SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.aiStandardSurface7SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.aiStandardSurface7SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.lambert3SG}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/sci_-_fi_flying_robot..glb')

export default RoboBot